-- 大エリア表示名のシード（HotPepper large_area と対応）
-- fetch-shops 未実行でもプルダウン等で日本語名を出せるようにする
INSERT INTO area_labels (code, name, parent_code, level, updated_at) VALUES
  ('Z011', '東京', NULL, 'large', datetime('now')),
  ('Z012', '神奈川', NULL, 'large', datetime('now')),
  ('Z013', '埼玉', NULL, 'large', datetime('now')),
  ('Z014', '千葉', NULL, 'large', datetime('now')),
  ('Z015', '茨城', NULL, 'large', datetime('now')),
  ('Z016', '栃木', NULL, 'large', datetime('now')),
  ('Z017', '群馬', NULL, 'large', datetime('now')),
  ('Z021', '北海道', NULL, 'large', datetime('now')),
  ('Z031', '宮城', NULL, 'large', datetime('now')),
  ('Z032', '山形', NULL, 'large', datetime('now')),
  ('Z033', '福島', NULL, 'large', datetime('now')),
  ('Z034', '青森', NULL, 'large', datetime('now')),
  ('Z035', '岩手', NULL, 'large', datetime('now')),
  ('Z036', '秋田', NULL, 'large', datetime('now')),
  ('Z041', '愛知', NULL, 'large', datetime('now')),
  ('Z042', '岐阜', NULL, 'large', datetime('now')),
  ('Z043', '三重', NULL, 'large', datetime('now')),
  ('Z044', '静岡', NULL, 'large', datetime('now')),
  ('Z051', '大阪', NULL, 'large', datetime('now')),
  ('Z052', '兵庫', NULL, 'large', datetime('now')),
  ('Z053', '京都', NULL, 'large', datetime('now')),
  ('Z054', '滋賀', NULL, 'large', datetime('now')),
  ('Z055', '奈良', NULL, 'large', datetime('now')),
  ('Z056', '和歌山', NULL, 'large', datetime('now')),
  ('Z061', '岡山', NULL, 'large', datetime('now')),
  ('Z062', '広島', NULL, 'large', datetime('now')),
  ('Z063', '鳥取', NULL, 'large', datetime('now')),
  ('Z064', '島根', NULL, 'large', datetime('now')),
  ('Z065', '山口', NULL, 'large', datetime('now')),
  ('Z071', '福岡', NULL, 'large', datetime('now')),
  ('Z072', '佐賀', NULL, 'large', datetime('now')),
  ('Z073', '長崎', NULL, 'large', datetime('now')),
  ('Z074', '熊本', NULL, 'large', datetime('now')),
  ('Z075', '大分', NULL, 'large', datetime('now')),
  ('Z076', '宮崎', NULL, 'large', datetime('now')),
  ('Z077', '鹿児島', NULL, 'large', datetime('now')),
  ('Z078', '沖縄', NULL, 'large', datetime('now')),
  ('Z081', '新潟', NULL, 'large', datetime('now')),
  ('Z082', '長野', NULL, 'large', datetime('now')),
  ('Z083', '山梨', NULL, 'large', datetime('now')),
  ('Z091', '石川', NULL, 'large', datetime('now')),
  ('Z092', '福井', NULL, 'large', datetime('now')),
  ('Z093', '富山', NULL, 'large', datetime('now')),
  ('Z101', '香川', NULL, 'large', datetime('now')),
  ('Z102', '徳島', NULL, 'large', datetime('now')),
  ('Z103', '愛媛', NULL, 'large', datetime('now')),
  ('Z104', '高知', NULL, 'large', datetime('now'))
ON CONFLICT(code) DO UPDATE SET
  name = excluded.name,
  parent_code = excluded.parent_code,
  level = excluded.level,
  updated_at = excluded.updated_at;
