-- HotPepper large_area 現行コードに合わせて大エリア表示名を是正する。
-- 0003 は適用済みのため編集せず、本マイグレーションで UPSERT する。
-- （fetch-shops の API 同期後も、シード由来の旧コード表記が残る環境向け）
INSERT INTO area_labels (code, name, parent_code, level, updated_at) VALUES
  ('Z011', '東京', NULL, 'large', datetime('now')),
  ('Z012', '神奈川', NULL, 'large', datetime('now')),
  ('Z013', '埼玉', NULL, 'large', datetime('now')),
  ('Z014', '千葉', NULL, 'large', datetime('now')),
  ('Z015', '茨城', NULL, 'large', datetime('now')),
  ('Z016', '栃木', NULL, 'large', datetime('now')),
  ('Z017', '群馬', NULL, 'large', datetime('now')),
  ('Z021', '滋賀', NULL, 'large', datetime('now')),
  ('Z022', '京都', NULL, 'large', datetime('now')),
  ('Z023', '大阪', NULL, 'large', datetime('now')),
  ('Z024', '兵庫', NULL, 'large', datetime('now')),
  ('Z025', '奈良', NULL, 'large', datetime('now')),
  ('Z026', '和歌山', NULL, 'large', datetime('now')),
  ('Z031', '岐阜', NULL, 'large', datetime('now')),
  ('Z032', '静岡', NULL, 'large', datetime('now')),
  ('Z033', '愛知', NULL, 'large', datetime('now')),
  ('Z034', '三重', NULL, 'large', datetime('now')),
  ('Z041', '北海道', NULL, 'large', datetime('now')),
  ('Z051', '青森', NULL, 'large', datetime('now')),
  ('Z052', '岩手', NULL, 'large', datetime('now')),
  ('Z053', '宮城', NULL, 'large', datetime('now')),
  ('Z054', '秋田', NULL, 'large', datetime('now')),
  ('Z055', '山形', NULL, 'large', datetime('now')),
  ('Z056', '福島', NULL, 'large', datetime('now')),
  ('Z061', '新潟', NULL, 'large', datetime('now')),
  ('Z062', '富山', NULL, 'large', datetime('now')),
  ('Z063', '石川', NULL, 'large', datetime('now')),
  ('Z064', '福井', NULL, 'large', datetime('now')),
  ('Z065', '山梨', NULL, 'large', datetime('now')),
  ('Z066', '長野', NULL, 'large', datetime('now')),
  ('Z071', '鳥取', NULL, 'large', datetime('now')),
  ('Z072', '島根', NULL, 'large', datetime('now')),
  ('Z073', '岡山', NULL, 'large', datetime('now')),
  ('Z074', '広島', NULL, 'large', datetime('now')),
  ('Z075', '山口', NULL, 'large', datetime('now')),
  ('Z081', '徳島', NULL, 'large', datetime('now')),
  ('Z082', '香川', NULL, 'large', datetime('now')),
  ('Z083', '愛媛', NULL, 'large', datetime('now')),
  ('Z084', '高知', NULL, 'large', datetime('now')),
  ('Z091', '福岡', NULL, 'large', datetime('now')),
  ('Z092', '佐賀', NULL, 'large', datetime('now')),
  ('Z093', '長崎', NULL, 'large', datetime('now')),
  ('Z094', '熊本', NULL, 'large', datetime('now')),
  ('Z095', '大分', NULL, 'large', datetime('now')),
  ('Z096', '宮崎', NULL, 'large', datetime('now')),
  ('Z097', '鹿児島', NULL, 'large', datetime('now')),
  ('Z098', '沖縄', NULL, 'large', datetime('now'))
ON CONFLICT(code) DO UPDATE SET
  name = excluded.name,
  parent_code = excluded.parent_code,
  level = excluded.level,
  updated_at = excluded.updated_at;
